### ISSUE TITLE
How to obtain the value of clicked item using onMarkerClicked prop

### ISSUE THREAD

**Issue by iamanoopmk** [kadoshms/react-jvectormap#1]
Hi,

Thank you for writing this wrapper. Was really helpful. 

I have added some markers and onMarkerClick to the VectorMap. I am not able to figure out how to get the onclick data back form it. Could you please guide me? Following is my code

`                                             
<VectorMap map={'us_aea'}
                                                    backgroundColor="#EEEEEE"                                              
                                                    ref="map"
                                                    containerStyle={{
                                                        width: '100%',
                                                        height: '100%'
                                                    }}
                                                    markers ={markers}
                                                    onMarkerClick = {this.onMarkerClick.bind(this)}
                                                    containerClassName="map"
                                        />`

here markers is as follows

`var markers = [
            {latLng: [43.859,-96.006], name: 'area 1'},
            {latLng: [32.3257,-98.4342], name: 'area 2'},
            {latLng: [40.41336,-87.3032], name: 'area 3'}
        ]`

In jQuery we get index of the clicked marker. But if I try to bind any variable to the function it gives me an error. How to get the clicked index or its value?

**Comment by kadoshms** [comment]
From the onMarkerClick docs, you can see that the arguments passed when this method is invoked are (evt, id).
So you can just use the id to access the marker:

```
import React from 'react';
import { VectorMap } from '../lib';

const markers = [ {latLng: [43.859,-96.006], name: 'area 1'}, {latLng: [32.3257,-98.4342], name: 'area 2'}, {latLng: [40.41336,-87.3032], name: 'area 3'} ]

class App extends React.Component {

    changeBg() {
        this.refs.map.setBackgroundColor('red');
    }

    onMarkerClick(evt, id) {
        console.log(markers[id].name)
    }
    render() {

        return (
            <div style={{width: 500, height: 500}}>
                <VectorMap map={'us_aea'} backgroundColor="#EEEEEE"
                           ref="map" containerStyle={{ width: '100%', height: '100%' }}
                           markers ={markers}
                           onMarkerClick = {this.onMarkerClick.bind(this)} containerClassName="map" />


            </div>
        );
    }
}

export default App;
```

**Comment by iamanoopmk** [comment]
Thank you for your help
