### ISSUE TITLE
Map Request - Turkey

### ISSUE THREAD

**Issue by alperensavaskan** [kadoshms/react-jvectormap#105]
Could you add Turkey map?

[https://raw.githubusercontent.com/cbilgili/jVectorMap-Turkey/master/jquery-jvectormap-data-turkey-tr-en.js](url)
Does this js file work?

**Comment by kadoshms** [comment]
Hey there,
If you are using the new version (still alpha!) version of react-jvectormap, the map of Turkey is available via `@react-jvectormap/turkey`.
