### ISSUE TITLE
License

### ISSUE THREAD

**Issue by JStrebeyko** [kadoshms/react-jvectormap#12]
Hi there,
I am new to the licensing game, would like to use the module in my project.
jVectorMap swapped licenses from version 2.0.0 upwards and now uses "dual license" ([GNU/commercial](http://jvectormap.com/licenses-and-pricing/)) instead of MIT. TBH I can make no sense out of what I can and cannot do with jVectorMap and I assume it is the same for the react-jvectormap.

Can I use it in a project that might eventually be sold? If not, is there a way to set back the wrapped jVectorMap version to the 1.2.2 version, when it was all a free game?

Best, Kuba

**Comment by kadoshms** [comment]
@JStrebeyko thanks for bringing that up.
You are free to use this project for any purpose as long as it does not violate the Jvector-maps licence agreement.
