### ISSUE TITLE
Country code error in  WorldMill map

### ISSUE THREAD

**Issue by n-sikka** [kadoshms/react-jvectormap#123]
I saw a closed issue #120 and I've the exact same problem but with `Czech Republic`. The country code isn't a valid ISO code, it's `82a` 
Firstly it would be really great if I can understand the reasoning behind using these country codes instead of the standard ones. A lot of other countries also have the same issue. 

It's not possible to use a dataset that has country codes with the map because of this problem as it's not a standard country code. 

The issue #120 is resolved with the comment that the country codes were replaced and fixed but I guess it was just for that one specific country. 

Is it not possible to use the standard [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country codes for all the countries?

**Comment by kadoshms** [comment]
Well I'm not quite sure how this happend TBH ^^
anyway I went through all countries and fixed the corrupted codes, and publish it to `@react-jvectormap/world@1.1.2`
