### ISSUE TITLE
Please fix Indonesian map

### ISSUE THREAD

**Issue by mzulkiakbari** [kadoshms/react-jvectormap#137]
I have fixed indonesia map in idnMerc.json.
[idnMerc.json](https://github.com/kadoshms/react-jvectormap/files/13795427/idnMerc.json)
i can't to pull request because i am not collaborator yet. In packages @react-jvectormap/indonesia map showed is provinces not Indonesia country.

**Comment by kadoshms** [comment]
you can fork it and then open the pull request

**Comment by mzulkiakbari** [comment]
Okay
