### ISSUE TITLE
Map Request : Brazil!

### ISSUE THREAD

**Issue by yagomassiah** [kadoshms/react-jvectormap#18]
Hey, React is all over the place here in Brazil, it would be nice to have it.

**Comment by kadoshms** [comment]
You got it, thanks to https://github.com/paulofreitas/jvectormap-brazil-map 3c5013df578cb52829902e84a6295f64f891af6d

**Comment by yagomassiah** [comment]
Thank you @kadoshms you and @paulofreitas are the best!
