### ISSUE TITLE
Error with jvectormap when resize window

### ISSUE THREAD

**Issue by keshavhub** [kadoshms/react-jvectormap#21]
On resizing the browser window, the error shown on browser's console log:
Error: <g> attribute transform: Expected number, "scale(NaN) translate(N…".

Related issue:
https://github.com/creativetimofficial/ct-vue-paper-dashboard-pro/issues/12

![image](https://user-images.githubusercontent.com/17063511/52673936-b9bcec00-2ee7-11e9-807d-3fbbd35aadab.png)

**Comment by locmai0808** [comment]
I have the same problem as well.

**Comment by kadoshms** [comment]
Hey, thanks for reporting.
Seems like this issue is related directly to JvectorMap, and since this library is just a wrapper around it, I can't do anything at the moment, hopefully it will be fixed in the future :)
