### ISSUE TITLE
Zooming into a region

### ISSUE THREAD

**Issue by ivanha09** [kadoshms/react-jvectormap#31]
Is it possible to zoom into a region on the map like this?
https://codepen.io/michaelgermini/pen/QyjrZb

**Comment by kadoshms** [comment]
@ivanha09 you can always zoom with the zoom buttons / mousewheel.
Did I misunderstand :)

**Comment by ryadav-dd** [comment]
Can we zoom into a region by clicking on it, I see the setFocus method on mapObject, but the **_mapObj.$mapObject.setFocus({ region: 'asia_mill', animate: true, scale: 5 });_**, But it is throwing this error in the build file.
![Screenshot from 2020-10-15 10-48-01](https://user-images.githubusercontent.com/63899022/96080101-efdc1b80-0ed3-11eb-8ad8-a38f9932abbd.png). Can you help me out. Thank you in advance.
