### ISSUE TITLE
Is it possible to set an array of countries available to select?

### ISSUE THREAD

**Issue by GreatEarl** [kadoshms/react-jvectormap#33]
User story - I would like to make only certain countries clickable - let say I have data to display only for those not for all countries.

**Comment by kadoshms** [comment]
@GreatEarl 
You can always handle the `onRegionSelect/Click` based on your own needs.
Furthermore, you can always color these regions differently from the non selectable.
See example here: https://stackoverflow.com/questions/12934000/jvectormap-country-colors
