### ISSUE TITLE
Multi Drilldown Map

### ISSUE THREAD

**Issue by sethgoodluck** [kadoshms/react-jvectormap#41]
It would be sweet if something like this was implemented (as in jvector examples) 
http://jvectormap.com/examples/drill-down/

Reference code: 
https://github.com/bjornd/jvectormap/blob/master/src/multimap.js

**Comment by kadoshms** [comment]
@sethgoodluck indeed! will be considered

**Comment by hoossainalik** [comment]
@kadoshms Has this MultiMap Drill Down feature been implemented yet?

**Comment by ryadav-dd** [comment]
Where's the MultiMap Drill Down feature at?
Are you guys planning to release it anytime soon?
