### ISSUE TITLE
Is changing the map on state change supported?

### ISSUE THREAD

**Issue by mr1hm** [kadoshms/react-jvectormap#52]
i'm trying to change map on region click by setting the map prop to this.state.map and i'm getting this error:
```shell
Uncaught Error: Attempt to use map which was not loaded: us_aea
```

i'm rather new to working with libraries and i noticed that there's a some jquery involved as well. i wasn't sure how I could get that possibly working or if there is a workaround for it.

**Comment by kadoshms** [comment]
Since this project started as a mvp for a larger one, it doesnt yet support non-preloaded maps. Although, there are several open pull requests you can use that do :) (I will maybe merge them sometime in the future)

**Comment by mr1hm** [comment]
cool, i'll take a look through the PRs. thanks!
