### ISSUE TITLE
Map Request UK

### ISSUE THREAD

**Issue by khrishan** [kadoshms/react-jvectormap#55]
Hi

Would it be possible to have a drilled down version map of the UK - in particular, splitting the country into its member states (England, Scotland, Wales and Northern Ireland)?

Do you need SVGs in order to create the map? If so, would the maps from [react-vector-maps](https://react-vector-maps.netlify.com/maps) help?

Loving the repo so far. I'm personally using it as a scratchmap for my personal website. Keep up the good work!

**Comment by Ross-Savill** [comment]
Just throwing in my support for a UK-only map request 👍. Have subscribed to notifications about this issue.

Also loving this repo so far, many thanks guys for all your work 🙌.

**Comment by ThomasSaunders** [comment]
I'd also like this, please!
